package com.st10397576.sanewshub

import android.content.Context
import android.content.Intent
import android.util.Log
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInAccount
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider

/**
 * Helper class for Google Sign-In integration with Firebase.
 * Handles the SSO flow as required for Part 3.
 *
 * Reference: https://firebase.google.com/docs/auth/android/google-signin
 */
class GoogleSignInHelper(private val context: Context) {

    companion object {
        private const val TAG = "GoogleSignInHelper"
    }

    private val auth = FirebaseAuth.getInstance()

    // Configure Google Sign-In
    // Note: R.string.default_web_client_id is auto-generated by google-services.json
    private val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
        .requestIdToken(context.getString(R.string.default_web_client_id))
        .requestEmail()
        .build()

    val googleSignInClient: GoogleSignInClient = GoogleSignIn.getClient(context, gso)

    /**
     * Handles the result from Google Sign-In intent.
     * Called after user selects their Google account.
     *
     * @param data Intent data from the sign-in activity
     * @param onSuccess Callback executed on successful authentication
     * @param onFailure Callback executed on authentication failure
     */
    fun handleSignInResult(
        data: Intent?,
        onSuccess: (GoogleSignInAccount) -> Unit,
        onFailure: (Exception) -> Unit
    ) {
        try {
            // Get the signed-in account from the intent
            val task = GoogleSignIn.getSignedInAccountFromIntent(data)
            val account = task.getResult(ApiException::class.java)

            Log.d(TAG, "Google sign-in successful: ${account.email}")

            // Authenticate with Firebase using the Google account
            firebaseAuthWithGoogle(account, onSuccess, onFailure)

        } catch (e: ApiException) {
            // Google Sign-In failed
            Log.e(TAG, "Google sign-in failed with code: ${e.statusCode}", e)
            onFailure(e)
        }
    }

    /**
     * Authenticates with Firebase using Google credentials.
     * This links the Google account with Firebase Authentication.
     *
     * @param account Google account obtained from sign-in
     * @param onSuccess Callback executed on successful Firebase authentication
     * @param onFailure Callback executed on Firebase authentication failure
     */
    private fun firebaseAuthWithGoogle(
        account: GoogleSignInAccount,
        onSuccess: (GoogleSignInAccount) -> Unit,
        onFailure: (Exception) -> Unit
    ) {
        Log.d(TAG, "Authenticating with Firebase using Google account: ${account.email}")

        // Create Firebase credential from Google ID token
        val credential = GoogleAuthProvider.getCredential(account.idToken, null)

        // Sign in to Firebase with the credential
        auth.signInWithCredential(credential)
            .addOnSuccessListener {
                Log.d(TAG, "Firebase authentication successful for user: ${it.user?.email}")
                onSuccess(account)
            }
            .addOnFailureListener { exception ->
                Log.e(TAG, "Firebase authentication failed", exception)
                onFailure(exception)
            }
    }

    /**
     * Signs out the user from both Google and Firebase.
     * Use this when implementing logout functionality.
     *
     * @param onComplete Callback executed after sign-out is complete
     */
    fun signOut(onComplete: () -> Unit) {
        // Sign out from Firebase
        auth.signOut()

        // Sign out from Google
        googleSignInClient.signOut().addOnCompleteListener {
            Log.d(TAG, "User signed out from Google and Firebase")
            onComplete()
        }
    }
}